# Generated by Django 4.1.7 on 2023-03-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ufc_scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="kd1",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="kd2",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="str1",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="str2",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="sub1",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="sub2",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="td1",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="td2",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
